- name: Update packages.
  become: true
  yum:
    update_cache: yes

- name: Install nodejs, npm
  become: true
  shell: |
    curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -
    yum -y install nodejs npm

- name: Change node version
  become: true 
  shell: |
    npm install -g n 
    n 12.22.9

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
